### PR TITLE
Typehint Update

### PR DESCRIPTION
**Pull request by Ahmard**
Updated typehints to match the respected ones declared in docs.

### CODE REVIEW

**Comment by Ahmard** [comment]
Swoole\Server::addlistener() renamed to Swoole\Server::addListener() with respect to how it appears in docs.

**Comment by doubaokun** [comment]
@Ahmard please check the coding style errors report from ci. Thanks.

**Comment by Ahmard** [comment]
> @Ahmard please check the coding style errors report from ci. Thanks.
Okay

**Comment by Ahmard** [comment]
the style errors have been fixed

**Pull request merged**
