### PR TITLE
Moved `friendsofphp/php-cs-fixer` to dev-dependencies, as it should not be installed by consumers of this package

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by Ocramius** [comment]
Thanks @doubaokun!

**Comment by Ocramius** [comment]
@doubaokun can you tag this, when you have a moment, please? :D

**Comment by doubaokun** [comment]
@Ocramius It is tagged as v4.10.1

**Comment by Ocramius** [comment]
Ah, sorry, didn't see that it was already picked up, thanks!

**Pull request merged**
